### PR TITLE
Developed version 1.0.13

### LINKED ISSUE #78: GUI backend should respond with 4xx code, not with 204 when requested thing is not found
For example, when trying to view a challenge with wrong challenge URL, and probably in a lot of other places.

### PR DESCRIPTION
**Pull request by denkv**
Improved the REST API of the UI. Improved the user account handling in the platform using the gitlab API. Added support for challenge leaderboards and open challenges. Fixes #78, #115, #118, #122, #137, #138 and #139.

### CODE REVIEW

File: hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/BenchmarksResources.java [hunk 1]
```diff
@@ -77,37 +85,46 @@ public BenchmarkBean getById(@Context SecurityContext sc, @PathParam("id") Strin
...
+            PlatformControllerClient client = PlatformControllerClientSingleton.getInstance();
+            if (client == null) {
+                throw new GUIBackendException("Couldn't connect to platform controller.");
+            }
+            String id = client.submitBenchmark(model);
+            return Response.ok(new SubmitResponseBean(id)).build();
+        } catch (Exception e) {
+            SubmitResponseBean error = new SubmitResponseBean();
+            error.setError(e.getMessage());
+            //TODO use error status code
```
Comment (yamalight) [inline hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/BenchmarksResources.java]: Shouldn't this be done instead of leaving `TODO` here?
